server:
  port: 8080
spring:
  profiles:
    include: datasource-config,project-config
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML5

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

